name: darooyar
description: A prescription analysis app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  lottie: ^2.6.0
  form_builder_validators: ^11.0.0
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.1.14
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
